spring.application.name=url-shortener

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5433/url_shortener}
spring.datasource.username=${DB_USERNAME:url_admin}
spring.datasource.password=${DB_PASSWORD:url_password}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}